### ISSUE TITLE
Final submission Final Project of Chengwei Wang

### ISSUE THREAD

**Issue by ChengweiWang3210** [QMSS-G5072-2020/Final_Project_cw3210#1]
Hi @SUN-Wenjun @lonadai0121 @tbrambor,
Here's my final project:
a0ab47f2ca192aecd33c624874c0e4b1dcbad366
Thank you for reviewing it.

**Comment by lonadai0121** [comment]
4/5 very good project: The difficulty or breadth of the functionality or data acquisition are substantially above average. 
3/3 well commented and documented
3/3 The code is efficient, correct, and minimal
3/3 The package structure is clear, easy to follow, and closely matches the structure discussed in class.
3/3 The package, data, and functions’ documentation is clear and easy to follow. 
3/3 The package installs without problems.
3/3 The package contains automated testing of at least some of the main functions and these tests run without errors.
